### ISSUE TITLE
how to use the different messaging methods

### ISSUE THREAD

**Issue by santo74** [fatihcode/seneca-nats-transport#1]
Does this library support all the different messaging methods from nats (pub/sub, request/reply, queuing)?
If so, how can I specify which method I want to use, e.g. how can I use queuing with this library?

**Comment by devfacet** [comment]
Currently it only supports `pub/sub` pattern. But I'm thinking to implement other messaging patterns in a few weeks.

**Comment by santo74** [comment]
Ok, that's what I thought indeed after looking at the source code.
Would be nice to have the other methods as well.
I'll keep an eye on the repository.
Thanks.

**Comment by patrickschlaepfer** [comment]
Does it work with "pining"? Somethink like:   .listen({ type: 'nats', pin: 'role:patient' })
